[build]
  publish = "dist"
  command = "npm build:functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 3000
  publish = "dist"
  autoLaunch = true